[2025-08-30T14:49:58.807+0000] {processor.py:161} INFO - Started process (PID=3275) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:49:58.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:49:58.821+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:49:58.811+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:49:58.855+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:49:58.850+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:49:58.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:49:59.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.945 seconds
[2025-08-30T14:50:29.902+0000] {processor.py:161} INFO - Started process (PID=3280) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:50:29.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:50:29.907+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:50:29.906+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:50:29.936+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:50:29.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:50:29.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:50:29.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.107 seconds
[2025-08-30T14:51:00.120+0000] {processor.py:161} INFO - Started process (PID=3285) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:51:00.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:51:00.124+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:51:00.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:51:00.144+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:51:00.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:51:00.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:51:00.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.447 seconds
[2025-08-30T14:51:31.140+0000] {processor.py:161} INFO - Started process (PID=3290) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:51:31.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:51:31.144+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:51:31.144+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:51:31.182+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:51:31.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:51:31.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:51:31.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.107 seconds
[2025-08-30T14:52:01.377+0000] {processor.py:161} INFO - Started process (PID=3295) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:52:01.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:52:01.384+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:52:01.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:52:01.409+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:52:01.404+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:52:01.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:52:01.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.097 seconds
[2025-08-30T14:52:31.601+0000] {processor.py:161} INFO - Started process (PID=3300) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:52:31.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:52:31.606+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:52:31.605+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:52:31.631+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:52:31.625+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:52:31.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:52:31.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.082 seconds
[2025-08-30T14:53:01.949+0000] {processor.py:161} INFO - Started process (PID=3305) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:01.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:53:01.953+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:53:01.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:01.983+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:53:01.979+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:53:01.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:02.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.085 seconds
[2025-08-30T14:53:32.178+0000] {processor.py:161} INFO - Started process (PID=3310) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:32.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:53:32.181+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:53:32.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:32.201+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:53:32.197+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:53:32.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:32.230+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-30T14:53:45.363+0000] {processor.py:161} INFO - Started process (PID=3315) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:45.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:53:45.366+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:53:45.365+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:45.424+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:53:45.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:53:45.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:53:45.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.101 seconds
[2025-08-30T14:54:15.594+0000] {processor.py:161} INFO - Started process (PID=3320) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:54:15.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:54:15.597+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:54:15.597+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:54:15.617+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:54:15.613+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:54:15.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:54:15.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.078 seconds
[2025-08-30T14:54:45.891+0000] {processor.py:161} INFO - Started process (PID=3325) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:54:45.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:54:45.894+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:54:45.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:54:45.910+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:54:45.907+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:54:45.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:54:46.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.157 seconds
[2025-08-30T14:55:16.154+0000] {processor.py:161} INFO - Started process (PID=3330) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:55:16.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:55:16.157+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:55:16.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:55:16.180+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:55:16.175+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:55:16.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:55:16.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.788 seconds
[2025-08-30T14:55:47.219+0000] {processor.py:161} INFO - Started process (PID=3335) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:55:47.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:55:47.221+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:55:47.221+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:55:47.244+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:55:47.240+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:55:47.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:55:47.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T14:56:17.435+0000] {processor.py:161} INFO - Started process (PID=3340) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:56:17.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:56:17.438+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:56:17.437+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:56:17.453+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:56:17.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:56:17.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:56:17.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.055 seconds
[2025-08-30T14:56:47.722+0000] {processor.py:161} INFO - Started process (PID=3345) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:56:47.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:56:47.725+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:56:47.724+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:56:47.742+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:56:47.739+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:56:47.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:56:47.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T14:57:17.963+0000] {processor.py:161} INFO - Started process (PID=3350) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:57:17.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:57:17.966+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:57:17.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:57:17.985+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:57:17.981+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:57:17.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:57:18.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.055 seconds
[2025-08-30T14:57:48.298+0000] {processor.py:161} INFO - Started process (PID=3355) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:57:48.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:57:48.301+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:57:48.301+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:57:48.337+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:57:48.331+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:57:48.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:57:48.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.209 seconds
[2025-08-30T14:58:18.612+0000] {processor.py:161} INFO - Started process (PID=3360) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:58:18.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:58:18.614+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:58:18.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:58:18.653+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:58:18.643+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:58:18.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:58:18.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.108 seconds
[2025-08-30T14:58:49.026+0000] {processor.py:161} INFO - Started process (PID=3365) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:58:49.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:58:49.034+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:58:49.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:58:49.108+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:58:49.103+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:58:49.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:58:49.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.130 seconds
[2025-08-30T14:59:19.300+0000] {processor.py:161} INFO - Started process (PID=3370) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:59:19.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:59:19.303+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:59:19.302+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:59:19.321+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:59:19.316+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:59:19.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:59:19.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.061 seconds
[2025-08-30T14:59:49.594+0000] {processor.py:161} INFO - Started process (PID=3375) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:59:49.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T14:59:49.597+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:59:49.597+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:59:49.621+0000] {logging_mixin.py:188} INFO - [2025-08-30T14:59:49.617+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T14:59:49.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T14:59:50.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.677 seconds
[2025-08-30T15:00:20.588+0000] {processor.py:161} INFO - Started process (PID=3380) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:00:20.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:00:20.592+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:00:20.591+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:00:20.617+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:00:20.612+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:00:20.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:00:20.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.090 seconds
[2025-08-30T15:00:50.858+0000] {processor.py:161} INFO - Started process (PID=3385) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:00:50.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:00:50.863+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:00:50.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:00:50.904+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:00:50.899+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:00:50.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:00:50.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.098 seconds
[2025-08-30T15:01:21.132+0000] {processor.py:161} INFO - Started process (PID=3390) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:01:21.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:01:21.135+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:01:21.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:01:21.162+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:01:21.155+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:01:21.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:01:21.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.126 seconds
[2025-08-30T15:01:51.355+0000] {processor.py:161} INFO - Started process (PID=3395) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:01:51.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:01:51.357+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:01:51.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:01:51.375+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:01:51.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:01:51.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:01:51.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.204 seconds
[2025-08-30T15:02:21.751+0000] {processor.py:161} INFO - Started process (PID=3400) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:02:21.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:02:21.754+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:02:21.754+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:02:21.776+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:02:21.772+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:02:21.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:02:21.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.105 seconds
[2025-08-30T15:02:51.973+0000] {processor.py:161} INFO - Started process (PID=3405) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:02:51.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:02:51.976+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:02:51.976+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:02:51.999+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:02:51.995+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:02:52.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:02:52.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.120 seconds
[2025-08-30T15:03:22.259+0000] {processor.py:161} INFO - Started process (PID=3410) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:03:22.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:03:22.262+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:03:22.262+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:03:22.290+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:03:22.285+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:03:22.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:03:22.332+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.092 seconds
[2025-08-30T15:03:52.490+0000] {processor.py:161} INFO - Started process (PID=3415) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:03:52.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:03:52.493+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:03:52.492+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:03:52.511+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:03:52.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:03:52.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:03:52.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.111 seconds
[2025-08-30T15:04:22.892+0000] {processor.py:161} INFO - Started process (PID=3420) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:04:22.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:04:22.895+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:04:22.894+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:04:22.922+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:04:22.916+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:04:22.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:04:23.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.128 seconds
[2025-08-30T15:04:53.205+0000] {processor.py:161} INFO - Started process (PID=3425) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:04:53.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:04:53.208+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:04:53.208+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:04:53.232+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:04:53.227+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:04:53.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:04:53.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.062 seconds
[2025-08-30T15:05:23.505+0000] {processor.py:161} INFO - Started process (PID=3430) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:05:23.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:05:23.509+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:05:23.508+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:05:23.531+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:05:23.526+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:05:23.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:05:23.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.072 seconds
[2025-08-30T15:05:53.861+0000] {processor.py:161} INFO - Started process (PID=3435) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:05:53.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:05:53.864+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:05:53.864+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:05:53.890+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:05:53.884+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:05:53.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:05:53.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.069 seconds
[2025-08-30T15:06:24.129+0000] {processor.py:161} INFO - Started process (PID=3440) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:06:24.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:06:24.132+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:06:24.132+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:06:24.152+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:06:24.148+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:06:24.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:06:24.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.055 seconds
[2025-08-30T15:06:54.452+0000] {processor.py:161} INFO - Started process (PID=3445) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:06:54.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:06:54.455+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:06:54.455+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:06:54.486+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:06:54.481+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:06:54.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:06:54.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.066 seconds
[2025-08-30T15:07:24.770+0000] {processor.py:161} INFO - Started process (PID=3450) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:07:24.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:07:24.773+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:07:24.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:07:24.797+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:07:24.793+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:07:24.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:07:24.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.073 seconds
[2025-08-30T15:07:55.084+0000] {processor.py:161} INFO - Started process (PID=3455) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:07:55.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:07:55.087+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:07:55.087+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:07:55.114+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:07:55.109+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:07:55.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:07:55.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.068 seconds
[2025-08-30T15:08:25.408+0000] {processor.py:161} INFO - Started process (PID=3460) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:08:25.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:08:25.411+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:08:25.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:08:25.432+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:08:25.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:08:25.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:08:25.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-30T15:08:55.696+0000] {processor.py:161} INFO - Started process (PID=3465) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:08:55.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:08:55.699+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:08:55.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:08:55.722+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:08:55.719+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:08:55.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:08:55.751+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T15:09:25.957+0000] {processor.py:161} INFO - Started process (PID=3470) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:09:25.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:09:25.960+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:09:25.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:09:25.990+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:09:25.984+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:09:25.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:09:26.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.091 seconds
[2025-08-30T15:09:56.263+0000] {processor.py:161} INFO - Started process (PID=3475) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:09:56.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:09:56.266+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:09:56.266+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:09:56.290+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:09:56.284+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:09:56.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:09:56.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.081 seconds
[2025-08-30T15:10:26.618+0000] {processor.py:161} INFO - Started process (PID=3480) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:10:26.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:10:26.624+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:10:26.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:10:26.646+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:10:26.642+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:10:26.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:10:26.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.073 seconds
[2025-08-30T15:10:56.926+0000] {processor.py:161} INFO - Started process (PID=3485) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:10:56.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:10:56.930+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:10:56.929+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:10:56.949+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:10:56.945+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:10:56.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:10:56.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.061 seconds
[2025-08-30T15:11:27.350+0000] {processor.py:161} INFO - Started process (PID=3490) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:11:27.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:11:27.353+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:11:27.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:11:27.374+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:11:27.370+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:11:27.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:11:27.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.060 seconds
[2025-08-30T15:11:57.658+0000] {processor.py:161} INFO - Started process (PID=3495) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:11:57.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:11:57.661+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:11:57.661+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:11:57.682+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:11:57.678+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:11:57.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:11:57.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T15:12:27.980+0000] {processor.py:161} INFO - Started process (PID=3500) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:12:27.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:12:27.990+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:12:27.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:12:28.015+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:12:28.010+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:12:28.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:12:28.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.083 seconds
[2025-08-30T15:12:58.320+0000] {processor.py:161} INFO - Started process (PID=3505) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:12:58.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:12:58.324+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:12:58.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:12:58.347+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:12:58.341+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:12:58.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:12:58.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T15:13:28.691+0000] {processor.py:161} INFO - Started process (PID=3510) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:13:28.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:13:28.694+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:13:28.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:13:28.713+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:13:28.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:13:28.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:13:28.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.058 seconds
[2025-08-30T15:13:59.022+0000] {processor.py:161} INFO - Started process (PID=3515) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:13:59.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:13:59.025+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:13:59.025+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:13:59.048+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:13:59.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:13:59.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:13:59.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-30T15:14:29.425+0000] {processor.py:161} INFO - Started process (PID=3520) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:14:29.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:14:29.429+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:14:29.428+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:14:29.449+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:14:29.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:14:29.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:14:29.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.056 seconds
[2025-08-30T15:14:59.761+0000] {processor.py:161} INFO - Started process (PID=3525) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:14:59.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:14:59.764+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:14:59.763+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:14:59.801+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:14:59.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:14:59.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:14:59.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.074 seconds
[2025-08-30T15:15:30.187+0000] {processor.py:161} INFO - Started process (PID=3530) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:15:30.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:15:30.190+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:15:30.189+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:15:30.215+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:15:30.209+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:15:30.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:15:30.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.070 seconds
[2025-08-30T15:16:00.534+0000] {processor.py:161} INFO - Started process (PID=3535) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:16:00.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:16:00.538+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:16:00.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:16:00.562+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:16:00.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:16:00.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:16:00.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.061 seconds
[2025-08-30T15:16:30.893+0000] {processor.py:161} INFO - Started process (PID=3540) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:16:30.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:16:30.897+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:16:30.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:16:30.917+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:16:30.914+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:16:30.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:16:30.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-30T15:17:01.216+0000] {processor.py:161} INFO - Started process (PID=3545) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:17:01.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:17:01.219+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:17:01.218+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:17:01.240+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:17:01.236+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:17:01.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:17:01.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.058 seconds
[2025-08-30T15:17:31.571+0000] {processor.py:161} INFO - Started process (PID=3550) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:17:31.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:17:31.574+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:17:31.573+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:17:31.601+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:17:31.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:17:31.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:17:31.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.072 seconds
[2025-08-30T15:18:01.936+0000] {processor.py:161} INFO - Started process (PID=3555) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:18:01.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:18:01.939+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:18:01.939+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:18:01.962+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:18:01.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:18:01.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:18:01.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.062 seconds
[2025-08-30T15:18:32.279+0000] {processor.py:161} INFO - Started process (PID=3560) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:18:32.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:18:32.281+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:18:32.281+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:18:32.300+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:18:32.296+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:18:32.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:18:32.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.346 seconds
[2025-08-30T15:19:02.941+0000] {processor.py:161} INFO - Started process (PID=3565) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:19:02.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:19:02.944+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:19:02.944+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:19:02.961+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:19:02.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:19:02.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:19:02.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.057 seconds
[2025-08-30T15:19:33.275+0000] {processor.py:161} INFO - Started process (PID=3570) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:19:33.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:19:33.279+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:19:33.278+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:19:33.305+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:19:33.300+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:19:33.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:19:33.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-30T15:20:03.776+0000] {processor.py:161} INFO - Started process (PID=3575) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:20:03.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:20:03.779+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:20:03.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:20:03.805+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:20:03.799+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:20:03.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:20:03.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-30T15:20:34.063+0000] {processor.py:161} INFO - Started process (PID=3580) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:20:34.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:20:34.067+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:20:34.066+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:20:34.093+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:20:34.089+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:20:34.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:20:34.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-30T15:21:04.406+0000] {processor.py:161} INFO - Started process (PID=3585) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:21:04.407+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:21:04.409+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:21:04.409+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:21:04.427+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:21:04.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:21:04.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:21:04.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.055 seconds
[2025-08-30T15:21:34.763+0000] {processor.py:161} INFO - Started process (PID=3590) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:21:34.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:21:34.767+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:21:34.766+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:21:34.787+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:21:34.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:21:34.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:21:34.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.067 seconds
[2025-08-30T15:22:05.045+0000] {processor.py:161} INFO - Started process (PID=3595) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:22:05.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:22:05.050+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:22:05.049+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:22:05.075+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:22:05.068+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:22:05.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:22:05.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.075 seconds
[2025-08-30T15:22:35.396+0000] {processor.py:161} INFO - Started process (PID=3600) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:22:35.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:22:35.399+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:22:35.399+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:22:35.423+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:22:35.418+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:22:35.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:22:35.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.068 seconds
[2025-08-30T15:23:05.733+0000] {processor.py:161} INFO - Started process (PID=3605) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:23:05.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:23:05.737+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:23:05.736+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:23:05.760+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:23:05.757+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:23:05.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:23:05.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.061 seconds
[2025-08-30T15:23:36.044+0000] {processor.py:161} INFO - Started process (PID=3610) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:23:36.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:23:36.047+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:23:36.047+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:23:36.069+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:23:36.064+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:23:36.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:23:36.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.057 seconds
[2025-08-30T15:24:06.394+0000] {processor.py:161} INFO - Started process (PID=3615) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:24:06.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:24:06.397+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:24:06.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:24:06.421+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:24:06.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:24:06.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:24:06.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.061 seconds
[2025-08-30T15:24:36.672+0000] {processor.py:161} INFO - Started process (PID=3620) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:24:36.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:24:36.675+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:24:36.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:24:36.702+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:24:36.697+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:24:36.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:24:36.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-30T15:25:07.054+0000] {processor.py:161} INFO - Started process (PID=3625) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:25:07.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:25:07.057+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:25:07.057+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:25:07.082+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:25:07.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:25:07.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:25:07.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.066 seconds
[2025-08-30T15:25:37.403+0000] {processor.py:161} INFO - Started process (PID=3630) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:25:37.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:25:37.407+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:25:37.406+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:25:37.432+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:25:37.428+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:25:37.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:25:37.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.070 seconds
[2025-08-30T15:26:07.678+0000] {processor.py:161} INFO - Started process (PID=3635) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:26:07.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:26:07.681+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:26:07.681+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:26:07.703+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:26:07.699+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:26:07.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:26:07.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T15:26:38.033+0000] {processor.py:161} INFO - Started process (PID=3640) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:26:38.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:26:38.038+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:26:38.038+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:26:38.063+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:26:38.059+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:26:38.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:26:38.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T15:27:08.391+0000] {processor.py:161} INFO - Started process (PID=3645) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:27:08.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:27:08.396+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:27:08.395+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:27:08.421+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:27:08.416+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:27:08.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:27:08.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.082 seconds
[2025-08-30T15:27:38.680+0000] {processor.py:161} INFO - Started process (PID=3650) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:27:38.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:27:38.683+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:27:38.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:27:38.706+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:27:38.703+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:27:38.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:27:38.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.059 seconds
[2025-08-30T15:28:09.008+0000] {processor.py:161} INFO - Started process (PID=3655) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:28:09.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:28:09.013+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:28:09.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:28:09.035+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:28:09.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:28:09.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:28:09.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.082 seconds
[2025-08-30T15:28:39.311+0000] {processor.py:161} INFO - Started process (PID=3660) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:28:39.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:28:39.315+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:28:39.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:28:39.336+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:28:39.332+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:28:39.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:28:39.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T15:29:09.711+0000] {processor.py:161} INFO - Started process (PID=3665) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:29:09.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:29:09.714+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:29:09.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:29:09.740+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:29:09.735+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:29:09.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:29:09.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.062 seconds
[2025-08-30T15:29:39.992+0000] {processor.py:161} INFO - Started process (PID=3670) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:29:39.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:29:39.995+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:29:39.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:29:40.018+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:29:40.013+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:29:40.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:29:40.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.060 seconds
[2025-08-30T15:30:10.404+0000] {processor.py:161} INFO - Started process (PID=3675) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:30:10.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:30:10.408+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:30:10.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:30:10.431+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:30:10.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:30:10.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:30:10.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-30T15:30:40.781+0000] {processor.py:161} INFO - Started process (PID=3680) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:30:40.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:30:40.785+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:30:40.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:30:40.810+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:30:40.805+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:30:40.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:30:40.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.062 seconds
[2025-08-30T15:31:11.101+0000] {processor.py:161} INFO - Started process (PID=3685) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:31:11.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:31:11.104+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:31:11.104+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:31:11.130+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:31:11.126+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:31:11.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:31:11.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.066 seconds
[2025-08-30T15:31:41.448+0000] {processor.py:161} INFO - Started process (PID=3690) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:31:41.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:31:41.451+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:31:41.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:31:41.472+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:31:41.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:31:41.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:31:41.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.056 seconds
[2025-08-30T15:32:11.823+0000] {processor.py:161} INFO - Started process (PID=3695) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:32:11.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:32:11.825+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:32:11.825+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:32:11.848+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:32:11.843+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:32:11.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:32:11.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.060 seconds
[2025-08-30T15:32:42.173+0000] {processor.py:161} INFO - Started process (PID=3700) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:32:42.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:32:42.177+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:32:42.176+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:32:42.200+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:32:42.196+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:32:42.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:32:42.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.068 seconds
[2025-08-30T15:33:12.518+0000] {processor.py:161} INFO - Started process (PID=3705) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:33:12.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:33:12.521+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:33:12.521+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:33:12.545+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:33:12.540+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:33:12.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:33:12.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-30T15:33:42.865+0000] {processor.py:161} INFO - Started process (PID=3710) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:33:42.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:33:42.870+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:33:42.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:33:42.904+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:33:42.897+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:33:42.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:33:42.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.084 seconds
[2025-08-30T15:34:13.124+0000] {processor.py:161} INFO - Started process (PID=3715) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:34:13.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:34:13.126+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:34:13.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:34:13.148+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:34:13.143+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:34:13.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:34:13.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.067 seconds
[2025-08-30T15:34:43.456+0000] {processor.py:161} INFO - Started process (PID=3720) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:34:43.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:34:43.460+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:34:43.459+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:34:43.479+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:34:43.475+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:34:43.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:34:43.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.062 seconds
[2025-08-30T15:35:13.874+0000] {processor.py:161} INFO - Started process (PID=3725) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:35:13.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:35:13.878+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:35:13.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:35:13.904+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:35:13.900+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:35:13.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:35:13.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-30T15:35:44.150+0000] {processor.py:161} INFO - Started process (PID=3730) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:35:44.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:35:44.153+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:35:44.152+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:35:44.178+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:35:44.173+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:35:44.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:35:44.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-30T15:36:14.579+0000] {processor.py:161} INFO - Started process (PID=3735) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:36:14.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:36:14.582+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:36:14.582+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:36:14.607+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:36:14.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:36:14.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:36:14.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.066 seconds
[2025-08-30T15:36:44.934+0000] {processor.py:161} INFO - Started process (PID=3740) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:36:44.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:36:44.937+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:36:44.937+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:36:44.965+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:36:44.961+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:36:44.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:36:44.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.072 seconds
[2025-08-30T15:37:15.301+0000] {processor.py:161} INFO - Started process (PID=3745) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:37:15.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:37:15.305+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:37:15.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:37:15.329+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:37:15.325+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:37:15.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:37:15.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-30T15:37:45.705+0000] {processor.py:161} INFO - Started process (PID=3750) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:37:45.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:37:45.709+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:37:45.709+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:37:45.729+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:37:45.724+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:37:45.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:37:45.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.060 seconds
[2025-08-30T15:38:16.038+0000] {processor.py:161} INFO - Started process (PID=3755) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:38:16.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:38:16.041+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:38:16.041+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:38:16.063+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:38:16.059+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:38:16.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:38:16.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.061 seconds
[2025-08-30T15:38:46.347+0000] {processor.py:161} INFO - Started process (PID=3760) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:38:46.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:38:46.351+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:38:46.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:38:46.378+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:38:46.371+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:38:46.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:38:46.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-30T15:39:10.695+0000] {processor.py:161} INFO - Started process (PID=3765) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:10.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:39:10.698+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:39:10.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:10.732+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:39:10.727+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:39:10.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:10.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.081 seconds
[2025-08-30T15:39:28.898+0000] {processor.py:161} INFO - Started process (PID=3770) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:28.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:39:28.904+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:39:28.902+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:28.942+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:39:28.937+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:39:28.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:28.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.089 seconds
[2025-08-30T15:39:59.271+0000] {processor.py:161} INFO - Started process (PID=3775) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:59.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:39:59.274+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:39:59.274+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:59.299+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:39:59.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:39:59.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:39:59.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.061 seconds
[2025-08-30T15:40:29.598+0000] {processor.py:161} INFO - Started process (PID=3780) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:40:29.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:40:29.601+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:40:29.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:40:29.621+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:40:29.617+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:40:29.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:40:29.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.058 seconds
[2025-08-30T15:40:59.938+0000] {processor.py:161} INFO - Started process (PID=3785) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:40:59.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:40:59.942+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:40:59.941+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:40:59.962+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:40:59.956+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:40:59.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:40:59.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-30T15:41:30.270+0000] {processor.py:161} INFO - Started process (PID=3790) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:41:30.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:41:30.274+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:41:30.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:41:30.295+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:41:30.291+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:41:30.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:41:30.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.070 seconds
[2025-08-30T15:42:00.584+0000] {processor.py:161} INFO - Started process (PID=3795) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:42:00.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-30T15:42:00.587+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:42:00.586+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:42:00.609+0000] {logging_mixin.py:188} INFO - [2025-08-30T15:42:00.604+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-30T15:42:00.611+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-30T15:42:00.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.066 seconds
