[2025-08-26T15:30:32.986+0000] {processor.py:161} INFO - Started process (PID=2750) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:30:32.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:30:32.998+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:30:32.991+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:30:33.032+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:30:33.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:30:33.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:30:33.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.140 seconds
[2025-08-26T15:31:03.362+0000] {processor.py:161} INFO - Started process (PID=2755) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:31:03.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:31:03.367+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:31:03.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:31:03.404+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:31:03.385+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:31:03.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:31:03.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.127 seconds
[2025-08-26T15:31:33.572+0000] {processor.py:161} INFO - Started process (PID=2760) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:31:33.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:31:33.576+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:31:33.575+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:31:33.595+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:31:33.590+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:31:33.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:31:33.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.072 seconds
[2025-08-26T15:32:03.991+0000] {processor.py:161} INFO - Started process (PID=2765) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:32:03.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:32:03.996+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:32:03.995+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:32:04.026+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:32:04.021+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:32:04.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:32:04.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.087 seconds
[2025-08-26T15:32:34.237+0000] {processor.py:161} INFO - Started process (PID=2770) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:32:34.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:32:34.241+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:32:34.241+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:32:34.264+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:32:34.259+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:32:34.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:32:34.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.074 seconds
[2025-08-26T15:33:04.514+0000] {processor.py:161} INFO - Started process (PID=2775) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:33:04.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:33:04.517+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:33:04.516+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:33:04.548+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:33:04.542+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:33:04.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:33:04.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.075 seconds
[2025-08-26T15:33:34.740+0000] {processor.py:161} INFO - Started process (PID=2780) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:33:34.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:33:34.742+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:33:34.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:33:34.759+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:33:34.756+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:33:34.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:33:34.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.053 seconds
[2025-08-26T15:34:05.005+0000] {processor.py:161} INFO - Started process (PID=2785) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:34:05.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:34:05.008+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:34:05.008+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:34:05.033+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:34:05.029+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:34:05.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:34:05.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-26T15:34:35.240+0000] {processor.py:161} INFO - Started process (PID=2790) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:34:35.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:34:35.242+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:34:35.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:34:35.265+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:34:35.260+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:34:35.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:34:35.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.154 seconds
[2025-08-26T15:35:05.576+0000] {processor.py:161} INFO - Started process (PID=2795) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:35:05.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:35:05.579+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:35:05.578+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:35:05.597+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:35:05.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:35:05.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:35:07.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 2.329 seconds
[2025-08-26T15:35:38.228+0000] {processor.py:161} INFO - Started process (PID=2800) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:35:38.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:35:38.230+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:35:38.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:35:38.251+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:35:38.248+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:35:38.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:35:38.278+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.062 seconds
[2025-08-26T15:36:08.459+0000] {processor.py:161} INFO - Started process (PID=2805) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:36:08.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:36:08.462+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:36:08.462+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:36:08.489+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:36:08.484+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:36:08.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:36:08.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.076 seconds
[2025-08-26T15:36:38.791+0000] {processor.py:161} INFO - Started process (PID=2810) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:36:38.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:36:38.794+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:36:38.794+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:36:38.818+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:36:38.814+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:36:38.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:36:39.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.304 seconds
[2025-08-26T15:37:09.364+0000] {processor.py:161} INFO - Started process (PID=2815) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:37:09.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:37:09.367+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:37:09.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:37:09.391+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:37:09.387+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:37:09.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:37:09.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.078 seconds
[2025-08-26T15:37:39.599+0000] {processor.py:161} INFO - Started process (PID=2820) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:37:39.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:37:39.603+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:37:39.602+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:37:39.627+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:37:39.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:37:39.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:37:39.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.081 seconds
[2025-08-26T15:38:09.923+0000] {processor.py:161} INFO - Started process (PID=2825) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:38:09.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:38:09.927+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:38:09.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:38:09.949+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:38:09.944+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:38:09.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:38:09.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.074 seconds
[2025-08-26T15:38:40.189+0000] {processor.py:161} INFO - Started process (PID=2830) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:38:40.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:38:40.192+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:38:40.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:38:40.211+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:38:40.207+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:38:40.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:38:40.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-26T15:39:10.480+0000] {processor.py:161} INFO - Started process (PID=2835) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:39:10.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:39:10.483+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:39:10.483+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:39:10.513+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:39:10.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:39:10.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:39:10.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.104 seconds
[2025-08-26T15:39:40.721+0000] {processor.py:161} INFO - Started process (PID=2840) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:39:40.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:39:40.724+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:39:40.724+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:39:40.752+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:39:40.747+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:39:40.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:39:40.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.085 seconds
[2025-08-26T15:40:11.185+0000] {processor.py:161} INFO - Started process (PID=2845) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:40:11.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:40:11.188+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:40:11.187+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:40:11.211+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:40:11.206+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:40:11.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:40:11.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.074 seconds
[2025-08-26T15:40:41.427+0000] {processor.py:161} INFO - Started process (PID=2850) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:40:41.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:40:41.429+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:40:41.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:40:41.451+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:40:41.447+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:40:41.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:40:41.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-26T15:41:11.703+0000] {processor.py:161} INFO - Started process (PID=2855) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:41:11.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:41:11.706+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:41:11.706+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:41:11.731+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:41:11.725+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:41:11.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:41:11.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.075 seconds
[2025-08-26T15:41:41.934+0000] {processor.py:161} INFO - Started process (PID=2860) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:41:41.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:41:41.937+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:41:41.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:41:41.964+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:41:41.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:41:41.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:41:42.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.084 seconds
[2025-08-26T15:42:12.181+0000] {processor.py:161} INFO - Started process (PID=2865) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:42:12.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:42:12.184+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:42:12.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:42:12.207+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:42:12.200+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:42:12.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:42:12.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.067 seconds
[2025-08-26T15:42:42.448+0000] {processor.py:161} INFO - Started process (PID=2870) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:42:42.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:42:42.451+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:42:42.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:42:42.469+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:42:42.465+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:42:42.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:42:42.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.066 seconds
[2025-08-26T15:43:12.737+0000] {processor.py:161} INFO - Started process (PID=2875) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:43:12.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:43:12.741+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:43:12.740+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:43:12.760+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:43:12.755+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:43:12.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:43:12.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.073 seconds
[2025-08-26T15:43:42.980+0000] {processor.py:161} INFO - Started process (PID=2880) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:43:42.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:43:42.983+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:43:42.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:43:43.002+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:43:42.997+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:43:43.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:43:43.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.123 seconds
[2025-08-26T15:44:13.271+0000] {processor.py:161} INFO - Started process (PID=2885) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:44:13.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:44:13.273+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:44:13.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:44:13.294+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:44:13.290+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:44:13.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:44:13.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-26T15:44:43.497+0000] {processor.py:161} INFO - Started process (PID=2890) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:44:43.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:44:43.500+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:44:43.499+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:44:43.525+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:44:43.519+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:44:43.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:44:43.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.159 seconds
[2025-08-26T15:45:13.998+0000] {processor.py:161} INFO - Started process (PID=2895) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:45:14.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:45:14.003+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:45:14.002+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:45:14.023+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:45:14.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:45:14.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:45:14.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.076 seconds
[2025-08-26T15:45:44.242+0000] {processor.py:161} INFO - Started process (PID=2900) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:45:44.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:45:44.245+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:45:44.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:45:44.272+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:45:44.267+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:45:44.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:45:44.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.187 seconds
[2025-08-26T15:46:14.587+0000] {processor.py:161} INFO - Started process (PID=2905) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:46:14.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:46:14.591+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:46:14.590+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:46:14.613+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:46:14.610+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:46:14.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:46:14.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.067 seconds
[2025-08-26T15:46:44.966+0000] {processor.py:161} INFO - Started process (PID=2910) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:46:44.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:46:44.971+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:46:44.970+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:46:45.000+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:46:44.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:46:45.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:46:45.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.085 seconds
[2025-08-26T15:47:15.209+0000] {processor.py:161} INFO - Started process (PID=2915) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:47:15.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:47:15.211+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:47:15.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:47:15.236+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:47:15.231+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:47:15.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:47:15.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.071 seconds
[2025-08-26T15:47:45.577+0000] {processor.py:161} INFO - Started process (PID=2920) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:47:45.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:47:45.589+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:47:45.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:47:45.608+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:47:45.602+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:47:45.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:47:45.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.103 seconds
[2025-08-26T15:48:15.808+0000] {processor.py:161} INFO - Started process (PID=2925) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:48:15.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:48:15.811+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:48:15.811+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:48:15.831+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:48:15.827+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:48:15.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:48:15.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.075 seconds
[2025-08-26T15:48:46.126+0000] {processor.py:161} INFO - Started process (PID=2930) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:48:46.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:48:46.129+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:48:46.129+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:48:46.150+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:48:46.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:48:46.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:48:46.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.060 seconds
[2025-08-26T15:49:16.382+0000] {processor.py:161} INFO - Started process (PID=2935) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:49:16.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:49:16.384+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:49:16.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:49:16.401+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:49:16.398+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:49:16.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:49:16.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.052 seconds
[2025-08-26T15:49:46.825+0000] {processor.py:161} INFO - Started process (PID=2940) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:49:46.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:49:46.828+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:49:46.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:49:46.857+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:49:46.852+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:49:46.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:49:46.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.071 seconds
[2025-08-26T15:50:17.223+0000] {processor.py:161} INFO - Started process (PID=2945) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:50:17.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:50:17.227+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:50:17.226+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:50:17.257+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:50:17.250+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:50:17.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:50:17.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.079 seconds
[2025-08-26T15:50:47.482+0000] {processor.py:161} INFO - Started process (PID=2950) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:50:47.484+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:50:47.487+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:50:47.486+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:50:47.510+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:50:47.505+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:50:47.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:50:47.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.083 seconds
[2025-08-26T15:51:17.800+0000] {processor.py:161} INFO - Started process (PID=2955) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:51:17.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:51:17.805+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:51:17.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:51:17.834+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:51:17.828+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:51:17.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:51:17.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.075 seconds
[2025-08-26T15:51:48.129+0000] {processor.py:161} INFO - Started process (PID=2960) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:51:48.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:51:48.132+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:51:48.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:51:48.155+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:51:48.150+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:51:48.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:51:48.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-26T15:52:18.476+0000] {processor.py:161} INFO - Started process (PID=2965) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:52:18.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:52:18.479+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:52:18.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:52:18.499+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:52:18.496+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:52:18.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:52:18.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.056 seconds
[2025-08-26T15:52:48.824+0000] {processor.py:161} INFO - Started process (PID=2970) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:52:48.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:52:48.826+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:52:48.826+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:52:48.848+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:52:48.845+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:52:48.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:52:48.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.057 seconds
[2025-08-26T15:53:19.150+0000] {processor.py:161} INFO - Started process (PID=2975) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:53:19.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:53:19.154+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:53:19.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:53:19.175+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:53:19.171+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:53:19.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:53:19.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.057 seconds
[2025-08-26T15:53:49.449+0000] {processor.py:161} INFO - Started process (PID=2980) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:53:49.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:53:49.454+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:53:49.453+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:53:49.481+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:53:49.476+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:53:49.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:53:49.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.132 seconds
[2025-08-26T15:54:19.756+0000] {processor.py:161} INFO - Started process (PID=2985) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:54:19.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:54:19.759+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:54:19.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:54:19.784+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:54:19.779+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:54:19.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:54:19.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.064 seconds
[2025-08-26T15:54:50.107+0000] {processor.py:161} INFO - Started process (PID=2990) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:54:50.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:54:50.110+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:54:50.110+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:54:50.132+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:54:50.127+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:54:50.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:54:50.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-26T15:55:20.436+0000] {processor.py:161} INFO - Started process (PID=2995) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:55:20.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:55:20.439+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:55:20.439+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:55:20.461+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:55:20.456+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:55:20.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:55:20.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.066 seconds
[2025-08-26T15:55:50.758+0000] {processor.py:161} INFO - Started process (PID=3000) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:55:50.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:55:50.764+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:55:50.763+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:55:50.788+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:55:50.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:55:50.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:55:50.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.091 seconds
[2025-08-26T15:56:21.137+0000] {processor.py:161} INFO - Started process (PID=3005) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:56:21.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:56:21.140+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:56:21.140+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:56:21.159+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:56:21.156+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:56:21.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:56:21.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.053 seconds
[2025-08-26T15:56:51.414+0000] {processor.py:161} INFO - Started process (PID=3010) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:56:51.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:56:51.418+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:56:51.418+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:56:51.440+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:56:51.436+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:56:51.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:56:51.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.073 seconds
[2025-08-26T15:57:21.691+0000] {processor.py:161} INFO - Started process (PID=3015) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:57:21.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:57:21.696+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:57:21.695+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:57:21.716+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:57:21.711+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:57:21.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:57:21.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.069 seconds
[2025-08-26T15:57:51.981+0000] {processor.py:161} INFO - Started process (PID=3020) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:57:51.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:57:51.985+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:57:51.984+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:57:52.006+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:57:52.003+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:57:52.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:57:52.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.060 seconds
[2025-08-26T15:58:22.329+0000] {processor.py:161} INFO - Started process (PID=3025) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:58:22.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:58:22.333+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:58:22.332+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:58:22.352+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:58:22.348+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:58:22.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:58:22.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.061 seconds
[2025-08-26T15:58:52.668+0000] {processor.py:161} INFO - Started process (PID=3030) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:58:52.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:58:52.671+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:58:52.671+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:58:52.694+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:58:52.690+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:58:52.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:58:52.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.066 seconds
[2025-08-26T15:59:22.944+0000] {processor.py:161} INFO - Started process (PID=3035) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:59:22.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:59:22.948+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:59:22.947+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:59:22.970+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:59:22.966+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:59:22.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:59:22.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.060 seconds
[2025-08-26T15:59:53.246+0000] {processor.py:161} INFO - Started process (PID=3040) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:59:53.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T15:59:53.251+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:59:53.250+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:59:53.272+0000] {logging_mixin.py:188} INFO - [2025-08-26T15:59:53.268+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T15:59:53.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T15:59:53.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.065 seconds
[2025-08-26T16:00:23.605+0000] {processor.py:161} INFO - Started process (PID=3045) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:00:23.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T16:00:23.608+0000] {logging_mixin.py:188} INFO - [2025-08-26T16:00:23.608+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:00:23.631+0000] {logging_mixin.py:188} INFO - [2025-08-26T16:00:23.626+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T16:00:23.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:00:23.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.058 seconds
[2025-08-26T16:00:53.885+0000] {processor.py:161} INFO - Started process (PID=3050) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:00:53.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T16:00:53.889+0000] {logging_mixin.py:188} INFO - [2025-08-26T16:00:53.888+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:00:53.912+0000] {logging_mixin.py:188} INFO - [2025-08-26T16:00:53.908+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T16:00:53.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:00:53.992+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.118 seconds
[2025-08-26T16:01:24.231+0000] {processor.py:161} INFO - Started process (PID=3055) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:01:24.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T16:01:24.234+0000] {logging_mixin.py:188} INFO - [2025-08-26T16:01:24.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:01:24.260+0000] {logging_mixin.py:188} INFO - [2025-08-26T16:01:24.256+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T16:01:24.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T16:01:24.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 0.063 seconds
[2025-08-26T19:01:42.477+0000] {processor.py:161} INFO - Started process (PID=3060) to work on /opt/airflow/dags/etl_salaries.py
[2025-08-26T19:01:42.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_salaries.py for tasks to queue
[2025-08-26T19:01:42.491+0000] {logging_mixin.py:188} INFO - [2025-08-26T19:01:42.490+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_salaries.py
[2025-08-26T19:01:42.526+0000] {logging_mixin.py:188} INFO - [2025-08-26T19:01:42.518+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_salaries.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_salaries.py", line 55, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresHook
ImportError: cannot import name 'PostgresHook' from 'airflow.providers.postgres.operators.postgres' (/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py)
[2025-08-26T19:01:42.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_salaries.py
[2025-08-26T19:01:44.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_salaries.py took 2.227 seconds
